### ISSUE TITLE
Q3 Roadmap 2023

### ISSUE THREAD

**Issue by coolaj86** [dashtesting/dash-payment-webhooks#11]
- [x] Are XPubs safe? Or aren't they?
   - "Parents are ALWAYS Private"
   - Parent XPub + Child Private Key = Parent XPrv, regardless of "hardening"
   - see also
     - https://github.com/dashhive/DashHD.js/issues/28
     - https://github.com/dashhive/DashHD.js/pull/29
- [x] XPub (or Wallet Phrase) per customer (Depth 4 XPub is sufficient)
- [x] Depth 3 or Depth 4 XPubs?
   - depth 3 is for internal Account auditing
   - depth 4 is for sharing with Contacts
- [ ] swap in new ZeroMQ and new RPC

**Comment by coolaj86** [comment]
# Are XPubs Safe

Each customer account should have its own XPub, which is generated from a hardened XPrv'.

- At the level of an XPrv' (depths 1-3), knowing an XPrv' reveals all children, but nothing about siblings or parents
- At the level of an XPrv/XPub (depth 4), knowing the XPub (Chain Code) and any child private key is equal to the XPrv
- At the level of an Key/Address (depth 5), knowing a public key (or address) reveals nothing, and knowing a key (without the parent XPub / Chain Code) reveals nothing about siblings

```text
                                 XPrv'/XPub'     XPrv/XPub    Key/Address
                                  (account)       (usage)       (index)
                                     /0'     ==>    /0     ==>     /0
              BIP44        Dash     /      (safe)                  /1
(seed)       (spec)       (coin)   /                               /2
  /m    ==>   /44'   ==>    /5'   /n'
                                  \
                                   \                               /2
                                    \                              /1
                                     \1'     ==>    /0     ==>     /0
```
